[package]
org = "thisaru"
name = "github_stats"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[persist]
datastore = "googlesheets"
module = "github_stats"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.googlesheets-native"
version = "1.2.0"

